postgres:
  image: postgres
  volumes:
    - ./volumes/data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
core:
  build: ./images/core
#  image: ddouglascarr/core
  links: 
    - postgres
#  volumes:
#    - ../liquid_feedback_core:/opt/liquid_feedback_core

# Core container for running init commands in
core_init:
  build: ./images/core
  links:
    - postgres
  entrypoint: ./keep-alive.sh
  command: please

frontend:
  build: ./images/frontend
#  image: ddouglascarr/frontend
  ports:
    - "8080:8080"
  links:
    - postgres
  volumes:
    - ./volumes/ssmtp:/etc/ssmtp
    - ./volumes/frontend_config:/opt/liquid_feedback_frontend/config


